-- Run this in Supabase SQL Editor (one-time) to create tables + RLS policies.
-- Note: Supabase already provides the database; this script creates schema objects in `public`.

begin;

-- Extensions (usually already enabled on Supabase, but safe to ensure)
create extension if not exists pgcrypto;

-- =========================
-- Categories
-- =========================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  -- null = global/default category (shared)
  user_id uuid null references auth.users (id) on delete cascade,
  name text not null,
  icon text not null default '',
  kind text not null default 'expense' check (kind in ('expense', 'income', 'both')),
  created_at timestamptz not null default now()
);

create index if not exists categories_user_id_idx on public.categories (user_id);

-- avoid duplicate category names per user (global categories are allowed to share names)
create unique index if not exists categories_user_name_uniq
  on public.categories (user_id, name)
  where user_id is not null;

alter table public.categories enable row level security;

-- Anyone signed-in can read global categories, and their own categories
drop policy if exists "categories_select_global_and_own" on public.categories;
create policy "categories_select_global_and_own"
on public.categories
for select
to authenticated
using (user_id is null or user_id = auth.uid());

-- Demo mode (NO AUTH): allow anon to read/write global categories (user_id is null)
drop policy if exists "categories_select_global_anon" on public.categories;
create policy "categories_select_global_anon"
on public.categories
for select
to anon
using (user_id is null);

drop policy if exists "categories_insert_global_anon" on public.categories;
create policy "categories_insert_global_anon"
on public.categories
for insert
to anon
with check (user_id is null);

drop policy if exists "categories_update_global_anon" on public.categories;
create policy "categories_update_global_anon"
on public.categories
for update
to anon
using (user_id is null)
with check (user_id is null);

drop policy if exists "categories_delete_global_anon" on public.categories;
create policy "categories_delete_global_anon"
on public.categories
for delete
to anon
using (user_id is null);

-- Users can insert/update/delete only their own categories (not global)
drop policy if exists "categories_insert_own" on public.categories;
create policy "categories_insert_own"
on public.categories
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "categories_update_own" on public.categories;
create policy "categories_update_own"
on public.categories
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "categories_delete_own" on public.categories;
create policy "categories_delete_own"
on public.categories
for delete
to authenticated
using (user_id = auth.uid());

-- =========================
-- Transactions
-- =========================
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  -- null = demo mode (no-auth). If you add auth later, store auth.uid() here.
  user_id uuid null references auth.users (id) on delete cascade,
  category_id bigint null references public.categories (id) on delete set null,
  kind text not null check (kind in ('expense', 'income')),
  amount_vnd bigint not null check (amount_vnd > 0),
  note text not null default '',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_occurred_idx on public.transactions (user_id, occurred_at desc);
create index if not exists transactions_user_category_idx on public.transactions (user_id, category_id);

alter table public.transactions enable row level security;

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own"
on public.transactions
for select
to authenticated
using (user_id = auth.uid());

-- Demo mode (NO AUTH): allow anon to read/write global transactions (user_id is null)
drop policy if exists "transactions_select_global_anon" on public.transactions;
create policy "transactions_select_global_anon"
on public.transactions
for select
to anon
using (user_id is null);

drop policy if exists "transactions_insert_global_anon" on public.transactions;
create policy "transactions_insert_global_anon"
on public.transactions
for insert
to anon
with check (user_id is null);

drop policy if exists "transactions_update_global_anon" on public.transactions;
create policy "transactions_update_global_anon"
on public.transactions
for update
to anon
using (user_id is null)
with check (user_id is null);

drop policy if exists "transactions_delete_global_anon" on public.transactions;
create policy "transactions_delete_global_anon"
on public.transactions
for delete
to anon
using (user_id is null);

drop policy if exists "transactions_insert_own" on public.transactions;
create policy "transactions_insert_own"
on public.transactions
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "transactions_update_own" on public.transactions;
create policy "transactions_update_own"
on public.transactions
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "transactions_delete_own" on public.transactions;
create policy "transactions_delete_own"
on public.transactions
for delete
to authenticated
using (user_id = auth.uid());

-- =========================
-- Budgets (optional)
-- =========================
create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  -- null = demo mode (no-auth). If you add auth later, store auth.uid() here.
  user_id uuid null references auth.users (id) on delete cascade,
  category_id bigint null references public.categories (id) on delete set null,
  month date not null, -- store as first day of month (e.g. 2026-05-01)
  limit_vnd bigint not null check (limit_vnd > 0),
  created_at timestamptz not null default now()
);

create unique index if not exists budgets_user_month_category_uniq
  on public.budgets (user_id, month, category_id);

create index if not exists budgets_user_month_idx
  on public.budgets (user_id, month desc);

alter table public.budgets enable row level security;

drop policy if exists "budgets_select_own" on public.budgets;
create policy "budgets_select_own"
on public.budgets
for select
to authenticated
using (user_id = auth.uid());

-- Demo mode (NO AUTH): allow anon to read/write global budgets (user_id is null)
drop policy if exists "budgets_select_global_anon" on public.budgets;
create policy "budgets_select_global_anon"
on public.budgets
for select
to anon
using (user_id is null);

drop policy if exists "budgets_insert_global_anon" on public.budgets;
create policy "budgets_insert_global_anon"
on public.budgets
for insert
to anon
with check (user_id is null);

drop policy if exists "budgets_update_global_anon" on public.budgets;
create policy "budgets_update_global_anon"
on public.budgets
for update
to anon
using (user_id is null)
with check (user_id is null);

drop policy if exists "budgets_delete_global_anon" on public.budgets;
create policy "budgets_delete_global_anon"
on public.budgets
for delete
to anon
using (user_id is null);

drop policy if exists "budgets_insert_own" on public.budgets;
create policy "budgets_insert_own"
on public.budgets
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "budgets_update_own" on public.budgets;
create policy "budgets_update_own"
on public.budgets
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "budgets_delete_own" on public.budgets;
create policy "budgets_delete_own"
on public.budgets
for delete
to authenticated
using (user_id = auth.uid());

-- =========================
-- Seed: global categories (from the UI defaults)
-- =========================
insert into public.categories (user_id, name, icon, kind)
values
  (null, 'Ăn uống', 'AU', 'expense'),
  (null, 'Cafe', 'CF', 'expense'),
  (null, 'Nhà cửa', 'NC', 'expense'),
  (null, 'Sức khỏe', 'SK', 'expense'),
  (null, 'Di chuyển', 'DC', 'expense'),
  (null, 'Mua sắm', 'MS', 'expense'),
  (null, 'Giải trí', 'GT', 'expense'),
  (null, 'Hóa đơn', 'HD', 'expense')
on conflict do nothing;

commit;

